### ISSUE TITLE
How to launch Web Interface to capture packets

### ISSUE THREAD

**Issue by shanthu123** [kspviswa/dpi-enabled-ovs#4]
Hi,
I am running ovs with ndpi. I have created virtual network with mininet like
h1,h2 and s1 connected as below,
h1 h1-eth0:s1-eth1
h2 h2-eth0:s1-eth2

i am pinging h1 ping h2
listening for pcap file for s1-eth1
able to see the packets through ./ndpiReader -i s1-eth1_capture.pcap
able to see ICMP packets.

But on the other hand how to see packets through WebInterface ? i.e as in dpi-ovs-data.html
Can you help me.

Regards,
Shanthkumar

**Comment by kspviswa** [comment]
you need to use json-webserver. Refer https://cloud.githubusercontent.com/assets/7476271/7811671/d4c92f88-03c9-11e5-9118-ff0ca5c334df.png 

http://kspviswa.github.io/dpi-enabled-ovs/
